version: "3"
services:
  app:
    container_name: habita
    restart: "no"
    volumes:
        - .:/home/meteor/app/
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: habita-mongo
    image: mongo
    volumes:
      - ../mongoDB/testapp:/data/db
    ports:
      - "27017:27017"
